Update new output for pyCheck program for ELK monitoring
k8-proxy/vmware-scripts pull request #48
Opened 2021-01-09 02:54 UTC by hongson1981

# Output format like this :
# -> Dec 23 12:11:43 78.159.113.57 ping 8.8.8.8: PASS 13.23
# Dec 23 12:11:43 : timestamp
# 78.159.113.57: host
# ping 8.8.8.8: checkpoint
# PASS: result
# 13.23: round trip time in ms

2021-01-09 11:02 UTC, MariuszFerdyn requested changes

2021-01-09 11:02 UTC, MariuszFerdyn commented on HealthCheck/pyCheck.py
> +    s.connect(("8.8.8.8", 80))
8.8.8.8, 80 - hardcoded?

2021-01-11 14:12 UTC, hongson1981 commented
@MariuszFerdyn , @mahnouman 
UPdate python code to resolve hardcode issue

2021-01-11 15:04 UTC, MariuszFerdyn commented
ok Can be merge.

2021-01-11 15:05 UTC, MariuszFerdyn commented
Can be merge.

2021-01-11 16:51 UTC, merged