Added automated ova deployment module for esxi - Not refactored
k8-proxy/vmware-scripts pull request #92
Opened 2021-01-25 10:34 UTC by nirvishek

Added utility scripts as well (will be relocated to proper locations) for getting vm info, uploading file and executing script inside deployed vm.

2021-01-26 15:05 UTC, dinis-cruz-gw requested changes
please see my nodes and MORE IMPORTANTLY please check the code on k8-vmware before adding it here

a lot of the code below has been refactored into that project. in fact the point of that project is to make sure that scripts/tools like this don't have a lot of code in it 

basically, part of what we want here is to either:
 - leverage the APIs already in k8-vmware APIs
 - improve the k8-vmware APIs
 - create really clean and useful k8-vmware APIs that dramatically reduce the code required to write scripts/tools like this

2021-01-26 15:05 UTC, dinis-cruz-gw commented on scripts/automated-deployment/ova_deployment/ovf_handler.py
> +
actually I think a good amount of this code is already part of the https://github.com/k8-proxy/k8-vmware/pull/33 

can you sync up with @samarthdd to make sure we are not duplicating code

2021-01-26 15:05 UTC, dinis-cruz-gw commented on scripts/automated-deployment/ova_deployment/tools/cli.py
> +    return parser
convert to https://typer.tiangolo.com/

2021-01-26 15:05 UTC, dinis-cruz-gw commented on scripts/automated-deployment/ova_deployment/tools/tasks.py
> +            pcfilter.Destroy()
there is already a class/method in k8-vmware for this

2021-01-28 19:35 UTC, nirvishek commented on scripts/automated-deployment/ova_deployment/ovf_handler.py
> +
@dinis-cruz-gw i have removed this file and now using it from the api itself.

2021-01-28 19:37 UTC, nirvishek commented on scripts/automated-deployment/ova_deployment/VM_deploy_ova.py
> +    return largestRp
@dinis-cruz-gw i have refactored this file to class, and the method on the main api is missing one part where i can provide vm name as the argument. will add that to the main API and create PR.

2021-02-17 08:46 UTC, merged